---
lesson: PrePro2
thema: Piping / Joins
knitr:
  opts_chunk: 
    collapse: true
execute: 
  echo: false   # set to true to show musterlösung
  output: false
code-fold: true
code-summary: "Musterlösung"
---


# Prepro 2: Übung B

```{r}
#| echo: true
#| code-fold: false

# Benötigte Packages
```

## Aufgabe 1

Gegeben sind die Daten von drei Sensoren (*sensor1.csv*, *sensor2.csv*, *sensor3.csv*). Lese die Datensätze ein.



```{r}
library("readr")

sensor1 <- read_delim("datasets/prepro/sensor1.csv")
sensor2 <- read_delim("datasets/prepro/sensor2.csv")
sensor3 <- read_delim("datasets/prepro/sensor3.csv")
```



## Aufgabe 2

Erstelle aus den 3 Dataframes einen einzigen Dataframe, welcher aussieht wie unten dargestellt. Nutze dafür zwei joins aus `dplyr`, um 3 `data.frames` miteinander zu verbinden. Bereinige im Anschluss die Spaltennamen ([wie geht das?](https://www.statology.org/how-to-rename-data-frame-columns-in-r/)).


```{r}
library("dplyr")

sensor1_2 <- full_join(sensor1, sensor2, "Datetime")

sensor1_2 <- rename(sensor1_2, sensor1 = Temp.x, sensor2 = Temp.y)

sensor_all <- full_join(sensor1_2, sensor3, by = "Datetime")

sensor_all <- rename(sensor_all, sensor3 = Temp)
```


```{r}
#| echo: false
#| output: true

knitr::kable(head(sensor_all))
```


