project: 
  type: book
  preview: 
      port: 5678
  execute-dir: project
  pre-render: pre-render.r

lang: de

format: 
  html:
    theme:
      light: [flatly]
      dark: [flatly, "misc/presenter.scss"]    
    highlight-style:
      light: misc/arrow-light.theme
      dark: misc/arrow-light.theme
    css: 
      - misc/custom.css
    bibliography: misc/bibliography.bib
    number-sections: false
    code-tools:
      source: false

execute:
  freeze: true
  error: false
  message: false
  warning: false



knitr:
  opts_chunk: 
    collapse: true
    #tidy: true
    
book:
  title: "Research Methods HS25"
  sidebar: 
    logo: images/zhaw_sw_neg.png
    collapse-level: 1
    style: floating
  reader-mode: true    
  # globbing would be cool. Wait for https://github.com/quarto-dev/quarto-cli/issues/1917 to be resolved 
  chapters:
    - index.qmd
    - part: PrePro.qmd
      chapters:
      - prepro/Prepro1_Vorbereitung.qmd
    #   - --
    #   - prepro/Prepro1_Demo.qmd
    #   - prepro/Prepro1_Uebung.qmd
    #   - --
    #   - prepro/Prepro2_Demo.qmd
    #   - prepro/Prepro2_Uebung_A.qmd
    #   - prepro/Prepro2_Uebung_B.qmd
    #   - --
    #   - prepro/Prepro3_Demo.qmd
    #   - prepro/Prepro3_Uebung.qmd
    # - part: InfoVis.qmd
    #   chapters:
    #   - infovis/Infovis1_Vorbereitung.qmd
    #   - --
    #   - infovis/Infovis1_Demo.qmd
    #   - infovis/Infovis1_Uebung.qmd
    #   - infovis/Infovis1_Script_eda.qmd
    #   - --
    #   - infovis/Infovis2_Uebung_A.qmd
    #   - infovis/Infovis2_Uebung_B.qmd
    # - part: Statistik.qmd
    #   chapters:
    #   - statistik/Statistik0_Vorbereitung.qmd
    #   - statistik/Statistik1_Demo.qmd
    #   - statistik/Statistik1_Uebung.qmd
    #   - statistik/Statistik2_Demo.qmd
    #   - statistik/Statistik2_Uebung.qmd
    #   - statistik/Statistik3_Demo.qmd
    #   - statistik/Statistik3_Uebung.qmd      
    #   - statistik/Statistik4_Demo.qmd
    #   - statistik/Statistik4_Uebung.qmd      
    #   - statistik/Statistik5_Demo.qmd
    #   - statistik/Statistik5_Uebung.qmd      
    #   - statistik/Statistik6_Demo.qmd
    #   - statistik/Statistik6_Uebung.qmd      
    #   - statistik/Statistik7_Demo.qmd
    #   - statistik/Statistik7_Uebung.qmd      
    #   - statistik/Statistik8_Demo.qmd
    #   - statistik/Statistik8_Uebung.qmd        
    # - part: RaumAn.qmd
    #   chapters:
    #   - rauman/Rauman0_Vorbereitung.qmd
    #   - --
    #   - rauman/Rauman1_Uebung_A.qmd
    #   - rauman/Rauman1_Uebung_B.qmd
    #   - --
    #   - rauman/Rauman2_Uebung_A.qmd
    #   - rauman/Rauman2_Uebung_B.qmd
    #   - --
    #   - rauman/Rauman3_Uebung_A.qmd
    #   - rauman/Rauman3_Uebung_B.qmd
    #   - rauman/Rauman3_Uebung_C.qmd
    #   - --
    #   - rauman/Rauman4_Uebung_A.qmd
    #   - --
    #   - rauman/Rauman5_Uebung_A.qmd
    #   - rauman/Rauman5_Uebung_B.qmd
    # - part: "Fallstudie S"
    #   chapters:
    #   - fallstudie_s/0_Vorbereitung.qmd
    #   - --
    #   - fallstudie_s/1_Einführung.qmd
    #   - fallstudie_s/2_Besuchermonitoring.qmd
    #   - --
    #   - fallstudie_s/3_Aufgabenstellung_WPZ.qmd
    #   - --
    #   - fallstudie_s/4_Projektierung.qmd
    #   - fallstudie_s/5_Datenverarbeitung.qmd
    #   - fallstudie_s/6_Deskriptive_Analysen.qmd
    #   - fallstudie_s/7_Multivariate_Modelle.qmd
    # - part: "Fallstudie N"
    #   chapters:
    #   - fallstudie_n/1_Vorbemerkung.qmd
    #   - fallstudie_n/2_Datenverarbeitung.qmd
    #   - fallstudie_n/3_Berechnung_Homeranges.qmd
    #   - fallstudie_n/4_Multivariate_Modelle.qmd
    #   - fallstudie_n/5_Variablenselektion.qmd
    #   - fallstudie_n/6_Guete_und_Diagnostics.qmd
      #- --
      #- fallstudie_n/7_Modelle_mit_Nutzungsintensitaet.qmd
    - "References.qmd"
